config/routes.rb
Rails.application.routes.draw do
  resources :estudios
  resources :estudio_types
  root 'home#index'
  
  resources :pacientes
  devise_for :users
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/estudio.rb
class Estudio < ApplicationRecord

    belongs_to :paciente
    belongs_to :estudio_type

end

app/models/estudio_type.rb
class EstudioType < ApplicationRecord

    has_many :estudios
    has_many :pacientes, through: :estudios 

    def nom
        code + " - " + name
    end
end

app/models/paciente.rb
class Paciente < ApplicationRecord

    has_many :estudios
    has_many :estudio_types, through: :estudios 

    def full_name
        first_name + " " + last_name
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/estudio_types_controller.rb
class EstudioTypesController < ApplicationController
  before_action :set_estudio_type, only: %i[ show edit update destroy ]

  # GET /estudio_types or /estudio_types.json
  def index
    @estudio_types = EstudioType.all
  end

  # GET /estudio_types/1 or /estudio_types/1.json
  def show
  end

  # GET /estudio_types/new
  def new
    @estudio_type = EstudioType.new
  end

  # GET /estudio_types/1/edit
  def edit
  end

  # POST /estudio_types or /estudio_types.json
  def create
    @estudio_type = EstudioType.new(estudio_type_params)

    respond_to do |format|
      if @estudio_type.save
        format.html { redirect_to @estudio_type, notice: "Estudio type was successfully created." }
        format.json { render :show, status: :created, location: @estudio_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @estudio_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estudio_types/1 or /estudio_types/1.json
  def update
    respond_to do |format|
      if @estudio_type.update(estudio_type_params)
        format.html { redirect_to @estudio_type, notice: "Estudio type was successfully updated." }
        format.json { render :show, status: :ok, location: @estudio_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @estudio_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estudio_types/1 or /estudio_types/1.json
  def destroy
    @estudio_type.destroy
    respond_to do |format|
      format.html { redirect_to estudio_types_url, notice: "Estudio type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estudio_type
      @estudio_type = EstudioType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def estudio_type_params
      params.require(:estudio_type).permit(:name, :code, :instructions)
    end
end

app/controllers/estudios_controller.rb
class EstudiosController < ApplicationController
  before_action :set_estudio, only: %i[ show edit update destroy ]

  # GET /estudios or /estudios.json
  def index
    @estudios = Estudio.all
  end

  # GET /estudios/1 or /estudios/1.json
  def show
  end

  # GET /estudios/new
  def new
    @estudio = Estudio.new
    
  end

  # GET /estudios/1/edit
  def edit
  end

  # POST /estudios or /estudios.json
  def create
    @estudio = Estudio.new(estudio_params)

    respond_to do |format|
      if @estudio.save
        format.html { redirect_to @estudio, notice: "Estudio was successfully created." }
        format.json { render :show, status: :created, location: @estudio }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @estudio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estudios/1 or /estudios/1.json
  def update
    respond_to do |format|
      if @estudio.update(estudio_params)
        format.html { redirect_to @estudio, notice: "Estudio was successfully updated." }
        format.json { render :show, status: :ok, location: @estudio }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @estudio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estudios/1 or /estudios/1.json
  def destroy
    @estudio.destroy
    respond_to do |format|
      format.html { redirect_to estudios_url, notice: "Estudio was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estudio
      @estudio = Estudio.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def estudio_params
      params.require(:estudio).permit(:date, :paciente_id, :estudio_type_id, :comments, :status)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  before_action :set_paciente, only: %i[ show edit update destroy ]

  # GET /pacientes or /pacientes.json
  def index

    @q = Paciente.ransack(params[:q])
    @pacientes = @q.result(distinct: true)

  end

  # GET /pacientes/1 or /pacientes/1.json
  def show
  end

  # GET /pacientes/new
  def new
    @paciente = Paciente.new
  end

  # GET /pacientes/1/edit
  def edit
  end

  # POST /pacientes or /pacientes.json
  def create
    @paciente = Paciente.new(paciente_params)

    respond_to do |format|
      if @paciente.save
        format.html { redirect_to @paciente, notice: "Paciente was successfully created." }
        format.json { render :show, status: :created, location: @paciente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacientes/1 or /pacientes/1.json
  def update
    respond_to do |format|
      if @paciente.update(paciente_params)
        format.html { redirect_to @paciente, notice: "Paciente was successfully updated." }
        format.json { render :show, status: :ok, location: @paciente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacientes/1 or /pacientes/1.json
  def destroy
    @paciente.destroy
    respond_to do |format|
      format.html { redirect_to pacientes_url, notice: "Paciente was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paciente
      @paciente = Paciente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def paciente_params
      params.require(:paciente).permit(:first_name, :last_name, :phone, :email, :historial, :status_type, :study_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estudio_types_helper.rb
module EstudioTypesHelper
end

app/helpers/estudios_helper.rb
module EstudiosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/views/estudio_types/_form.html.erb
<%= form_with(model: estudio_type) do |form| %>
  <% if estudio_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(estudio_type.errors.count, "error") %> prohibited this estudio_type from being saved:</h2>

      <ul>
        <% estudio_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div>
  <div class="field">
    <%= form.label :name %>
    <br/>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <br/>
    <%= form.text_field :code, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :instructions %>
    <br/>
    <%= form.text_area :instructions, class: "form-control" %>
  </div>

  <br/>

  <div class="actions">
    <%= form.submit %>
  </div>
</div>
<% end %>

app/views/estudio_types/edit.html.erb
<h1>Editando tipo de estudio</h1>

<%= render 'form', estudio_type: @estudio_type %>

<br/>

<%= link_to 'Show', @estudio_type, class: "btn btn-secondary" %> |
<%= link_to 'Back', estudio_types_path, class: "btn btn-secondary"  %>

app/views/estudio_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tipos de estudio</h1>

<table class="table  table-light table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Nombre</th>
      <th>Codigo</th>
      <th>Instruciones</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estudio_types.each do |estudio_type| %>
      <tr>
        <td><%= link_to estudio_type.name, estudio_type %></td>
        <td><%= estudio_type.code %></td>
        <td><%= estudio_type.instructions %></td>
        <td><%= link_to 'Editar', edit_estudio_type_path(estudio_type), class:"btn btn-secondary" %></td>
        <td><%= link_to 'Eliminar', estudio_type, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estudio Type', new_estudio_type_path, class:"btn btn-secondary"%>

app/views/estudio_types/new.html.erb
<h1>Creando nuevo tipo de estudio</h1>

<%= render 'form', estudio_type: @estudio_type %>
<br/>
<%= link_to 'Atrás', estudio_types_path, class: "btn btn-secondary" %>

app/views/estudio_types/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
  <h1 class="display-4">
    <%= @estudio_type.nom %> 
  </h1>
  <p class="lead">
  <strong>Instrucciones:</strong> 
  <%= @estudio_type.instructions %>   
  </p>
  <br/>

<%= link_to 'Editar', edit_estudio_type_path(@estudio_type), class: "btn btn-secondary" %> |
<%= link_to 'Atrás', estudio_types_path, class: "btn btn-secondary" %>

app/views/estudios/_form.html.erb
<%= form_with(model: estudio) do |form| %>
  <% if estudio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(estudio.errors.count, "error") %> prohibited this estudio from being saved:</h2>

      <ul>
        <% estudio.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="container-fluid">>
    <%= form.label :date %>
    <br/>
    <%= form.datetime_select :date, class: "form-control" %>
  </div>
  <br/>

  <div class="container-fluid">>
    <%= form.label :comments %>
    <br/>
    <%= form.text_area :comments, class: "form-control" %>
  </div>
<br/>

  <div class="container-fluid">
    <div class ="control-group">
      <%=form.label :paciente, class: "control-group"%>
      <div class ="controls">
        <%= form.collection_select(:paciente_id, Paciente.find_each, :id, :first_name) %>
    <div class="actions">
  </div>

<br/>
  <div class ="control-group">
    <%=form.label "Tipo de estudio", class: "control-group"%>
    <div class ="controls">
      <%= form.collection_select(:estudio_type_id, EstudioType.all, :id, :name) %>

<br/>
<br/>

  <div class="control-group">
    <%= form.label "Estado Estudio: ", class: 'control-label' %>
    <div class = "controls">
      <%= form.select(:status, options_for_select([['Hecho', 'Hecho'],['Pendiente','Pendiente' ]]), {include_blank: true} )%>
  </div>


<br/>

<div class="actions">
    <%= form.submit %>
  </div>

  
<% end %>

app/views/estudios/edit.html.erb
<h1>Editar Estudio</h1>

<%= render 'form', estudio: @estudio %>
<br/>
<%= link_to 'Show', @estudio, class:"btn btn-secondary" %> |
<%= link_to 'Back', estudios_path, class:"btn btn-secondary"  %>

app/views/estudios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Estudios</h1>

<table class="table  table-light table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Fecha</th>
      <th>Paciente</th>
      <th>Tipo de estudio</th>
      <th>Comentarios</th>
      <th>Estado estudio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estudios.each do |estudio| %>
      <tr>
        <td><%= estudio.date %></td>
        <td><%= estudio.paciente.full_name %></td>
        <td><%= link_to estudio.estudio_type.nom, estudio %></td>
        <td><%= estudio.comments %></td>
        <td><%= estudio.status %></td>
        <td><%= link_to 'Ver', estudio, class: "btn btn-secondary" %></td>
        <td><%= link_to 'Editar', edit_estudio_path(estudio), class: "btn btn-secondary" %></td>
        <td><%= link_to 'Eliminar', estudio, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Estudio', new_estudio_path, class: "btn btn-secondary" %>

app/views/estudios/new.html.erb
<h1>New Estudio</h1>

<%= render 'form', estudio: @estudio %>

<%= link_to 'Back', estudios_path %>

app/views/estudios/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
  <h1 class="display-4">
    <%= @estudio.paciente.full_name %> |
    <%= @estudio.estudio_type.nom %>
  </h1>
  <p class="lead">
    <%= @estudio.date %> /
    <%= @estudio.comments %>
    
  </p>
  <br/>

<%= link_to 'Editar', edit_estudio_path(@estudio), class: "btn btn-secondary" %> |
<%= link_to 'Atrás', estudios_path, class: "btn btn-secondary" %>

app/views/home/index.html.erb
<h1>Control de Pacientes</h1>
<p>APP en progreso...</p>

app/views/layouts/_alerts.hmtl.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<div class="container-fluid">
    <a class="navbar-brand" href="#"><%= link_to "Inicio", root_path, class: "navbar-brand"%></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="#"><%= link_to "Ver Pacientes", pacientes_path, class: "nav-link active"%></a>
        </li>
        <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="#"><%= link_to "Ver Estudios", estudios_path, class: "nav-link active"%></a>
        </li>
        <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="#"><%= link_to "Ver tipos de estudio", estudio_types_path, class: "nav-link active"%></a>
        </li>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
    <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">

      <!-- Bootstrap CSS -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

      <title>Control de estudios</title>
    <head>
  
    </head>
    <body>
    <%= render 'layouts/navbar'%>
        <br/>
      <div>
          <% if notice %>
            <%= render 'layouts/alerts' %>
          <% end %>
      <div/>
      <%= yield %>


      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


      <!-- Optional JavaScript; choose one of the two! -->

      <!-- Option 1: Bootstrap Bundle with Popper -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

      <!-- Option 2: Separate Popper and Bootstrap JS -->
      <!--
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
      -->
    </body>
  </html>

app/views/pacientes/_form.html.erb
<%= form_with(model: paciente) do |form| %>
  <% if paciente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paciente.errors.count, "error") %> prohibited this paciente from being saved:</h2>

      <ul>
        <% paciente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div>
  <div class="field form-group">
    <% form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"Nombre(s)" %>
  </div>

  <br/>

  <div class="field form-group">
    <% form.label :last_name %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"Apellido" %>
  </div>

  <br/>
  
  <div class="field form-group">
    <%= form.text_field :phone, class: "form-control", placeholder:"# de teléfono" %>
  </div>

  <br/>

  <div class="field form-group">
        <%= form.text_field :email, class: "form-control", placeholder: "E-mail" %>
  </div>

  <br/>

  <div class="field">
    <%= form.label :historial %>
    <%= form.text_area :historial, class: "form-control" %>
  </div> 

  <br/>

  <div class="control-group">
    <%= form.label "Estado Estudio: ", class: 'control-label' %>
    <div class = "controls">
      <%= form.select(:status_type, options_for_select([['Hecho', 'Hecho'],['Pendiente','Pendiente' ]]), {include_blank: true} )%>
  </div>

  <br/>

  <div class="actions">
    <%= form.submit%>
  </div>

</div>
<% end %>

app/views/pacientes/_search_form.html.erb
<%= search_form_for @q do |f| %>

    <%= f.search_field :first_name_or_last_name_or_email_cont, placeholder: "Busque por nombre, apellido o correo electrónico." %>


<%= f.submit "Buscar" %>
<% end %>

app/views/pacientes/edit.html.erb
<h1>Editando Paciente</h1>

<%= render 'form', paciente: @paciente %>

<br/>

<%= link_to 'Ver', @paciente, class: "btn btn-secondary" %> |
<%= link_to 'Atrás', pacientes_path, class: "btn btn-secondary" %>

app/views/pacientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pacientes</h1>

<%= render 'pacientes/search_form'%>

<br/>

<table class="table  table-light table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th><%= sort_link(@q, :first_name, "Nombre(s)", default_order: :asc) %></th>
      <th><%= sort_link(@q, :last_name, "Apellido", default_order: :asc) %></th>
      <th>Phone</th>
      <th><%= sort_link(@q, :email, "E-Mail", default_order: :asc) %></th>      
      <th>Historial</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pacientes.each do |paciente| %>
      <tr>
        <td><%= link_to paciente.first_name, paciente %></td>
        <td><%= link_to paciente.last_name, paciente %></td>
        <td><%= paciente.phone %></td>
        <td><%= paciente.email %></td>
        <td><%= paciente.historial %></td>
        <td><%= link_to 'Editar', edit_paciente_path(paciente), class: "btn btn-secondary" %></td>
        <td><%= link_to 'Eliminar', paciente, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-danger"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Por Defecto', pacientes_path, class: "btn btn-secondary" %> |
<%= link_to 'Añadir paciente', new_paciente_path, class: "btn btn-secondary" %>

app/views/pacientes/new.html.erb
<h1>Nuevo paciente</h1>

<%= render 'form', paciente: @paciente %>

<%= link_to 'Atrás', pacientes_path, class:"btn btn-secondary" %>

app/views/pacientes/show.html.erb
<p id="notice"><%= notice %></p>


<div class="jumbotron">
  <h1 class="display-4">
    <%= @paciente.full_name %> 
  </h1>
  <p class="lead">
    <%= @paciente.phone %> /
    <%= @paciente.email %>
    
  </p>
  <br/>

<div class="jumbotron">
  <p class="lead">
    <%= @paciente.historial %>  
  </p>
    <br/>

<%= link_to 'Edit', edit_paciente_path(@paciente), class: "btn btn-secondary" %> |
<%= link_to 'Atrás', pacientes_path, class: "btn btn-secondary" %>